version: "3.3"
services:
  postgres:
    container_name: postgres_container
    image: postgres:15.3-alpine3.18
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
      - "-c"
      - "timezone=Europe/Moscow"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /usr/share/zoneinfo/Europe/Moscow:/etc/localtime:ro
    ports:
      - "5432:5432"
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U andy -d printdb"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
    restart: unless-stopped
#    deploy-configs:
#      resources:
#        limits:
#          cpus: '1'
#          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
#    deploy-configs:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 1G
    networks:
      - postgres

volumes:
  postgres-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge